version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: djangoproj/Dockerfile
    volumes:
      - ./djangoproj:/app:Z
    command: python /app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"

  webrtc:
    image: pionwebrtc/ion-sfu:latest-jsonrpc
    container_name: ion-sfu
    ports:
      - "7000:7000"
      - "5000-5200:5000-5200/udp"

