version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Streaming_App_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  django:
    build:
      context: .
      dockerfile: djangoproj/Dockerfile
    volumes:
      - ./djangoproj:/code
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  react:
    build:
      context: .
      dockerfile: reactapp/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - django

  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"

  webrtc:
    image: pionwebrtc/ion-sfu:latest-jsonrpc
    container_name: ion-sfu
    ports:
      - "7000:7000"
      - "5000-5200:5000-5200/udp"

volumes:
  postgres_data:
