# Generated by Django 5.0.2 on 2024-02-20 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(default='None', max_length=100, unique=True)),
                ('room_topic', models.CharField(default='None', max_length=100, unique=True)),
                ('room_description', models.TextField()),
                ('room_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
