# Generated by Django 5.0.2 on 2024-02-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
