# Generated by Django 5.0.2 on 2024-02-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_private_room_room_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='None', max_length=100, unique=True),
        ),
    ]
